# Generated by Django 3.2.22 on 2024-02-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Allergen'),
        ),
    ]
